a13xp0p0v/kernel-hardening-checker

- kconfig-hardened-check.py
With `--json` output will be formatted as array of arrays:
`[['CONFIG_BUG', 'y', 'defconfig', 'self_protection', 'OK'], ['CONFIG_STRICT_KERNEL_RWX', 'y', 'defconfig', 'self_protection', 'OK'], ...`
> add --json option

- kconfig-hardened-check.py
"CopperheadOS" is the project's legacy name which is now being used for a scam focused on attacking GrapheneOS, the true continuation.
https://twitter.com/DanielMicay/status/1171170734380654597
https://twitter.com/DanielMicay/status/1160831422908829696
https://old.reddit.com/r/CopperheadOS/comments/8qdnn3/goodbye/
https://github.com/yegortimoshenko/copperhead-takeover
> GrapheneOS is the continuation of CopperheadOS

- kconfig_hardened_check/__init__.py
The CONFIG_HARDEN_EL2_VECTORS Kconfig was removed in Linux 5.9: torvalds/linux@a59a2ed.
> Do not check CONFIG_HARDEN_EL2_VECTORS for v5.9+

- kconfig_hardened_check/__init__.py
Floppy driver was written many years ago. It was designed to
work in a single-threaded environment (many global variables)
and to work on real hardware which has significant delays
(floppy drives are slow). Nowadays, when we use virtual
devices (which are fast) and multi-core cpus, floppy driver
shows its problems including deadlocking/livelocking and
other security-related issues. However, we can't just
rewrite it because lack of real hardware and compatibility
with existing userspace tools, many of which rely on
undocumented driver behavior.
Here are some CVEs related to floppy driver:
- CVE-2014-1737 privileges escalation in FDRAWCMD ioctl
- CVE-2014-1738 info leak from kernel heap in FDRAWCMD ioctl
- CVE-2018-7755 kernel pointer lead in FDGETPRM ioctl
- CVE-2019-14283 integer overflow …
> Add BLK_DEV_FD

- kconfig_hardened_check/__init__.py
Both EFI_DISABLE_PCI_DMA and RESET_ATTACK_MITIGATION depend on EFI, but if EFI is not set, neither config is required.
Useful on embedded devices that use u-boot or similar instead of EFI.
> EFI mitigations can't be enabled if EFI is not set

- kconfig_hardened_check/__init__.py
ARCH_HAS_UBSAN_SANITIZE_ALL is not selected for arm arch, which prevents selection of CONFIG_UBSAN_SANITIZE_ALL
https://github.com/torvalds/linux/blob/master/arch/arm/Kconfig
https://github.com/torvalds/linux/blob/master/lib/Kconfig.ubsan
> UBSAN_SANITIZE_ALL not available on ARM

- kconfig_hardened_check/config_files/distros/get-nixos-kconfig.nix
Hello,
This nix script, when run with `nix-build get-nixos-kconfig.nix` will output 3 kernel configuration files (linux_latest, linux_hardened, and the linux_lts)  for NixOS
Has been tested on Ubuntu 20.04
#63  relevant
> add get-nixos-kconfig nix script

- README.md
- kernel_hardening_checker/__init__.py
`--kernel-version` option will extract the version in `/proc/version`. This is especially useful on embedded systems where `config.gz` doesn't always contain the kernel version
> add --kernel-version option

- kernel_hardening_checker/engine.py
- kernel_hardening_checker/test_engine.py
This pull request enhances the JSON output format, introducing a more structured and informative JSON schema. The changes include:
- Addition of a boolean `check_result` field to clearly indicate the success or failure of each check.
- Refinement of the output to an array of objects, where each object represents a check with detailed attributes such as:
- `option_name`: The name of the option being checked.
- `type`: The type of check performed (kconfig or cmdline).
- `desired_val`: The expected or desired value for the check.
- `decision`: The source for the decision (eg. grsec, clipos, defconfig).
- `reason`: A brief explanation for the decision.
- `check_result_text`: A human-readable description of the check result.
- `check_result`: A boolean indicating the success or failure of the …
> Improve JSON output format for enhanced processing

- kernel_hardening_checker/__init__.py
- kernel_hardening_checker/checks.py
Don't fail some sysctl checks if a config option already takes care of it
If called with both a kernel config file and a sysctl file, we can check the former to skip some sysctl checks that are not present because a config option has disabled it.
While at it, let `dev.tty.legacy_tiocsti` not be a failure if not found.  It was added in linux-6.2, so earlier versions will not have it.  Its absence alone is a soft indication that it can't be set.
It could be argued that any of the sysctl checks can be skipped if not found, but I still left the config checks in place, as an extra safeguard.
Switch the symbol used to check a root-generated sysctl file from `net.core.bpf_jit_harden` to `kernel.cad_pid` as the former is not present if JIT is disabled.
> Don't fail some sysctl checks if a config option already takes care of it

- kernel_hardening_checker/checks.py
References #109 
Added a sysctl io_uring_disabled check, which I believe should be set to 2 for complete disabling. Fully disabling this option reduces the attack surface, as a limited io_uring could still be exploited from rooted namespaces, such as unsecured Docker containers for example. Also, this approach is recommended by Grsecurity and has been implemented in kconfig as fully disabled.
> Add io_uring_disabled similar to CONFIG_IO_URING in kconfig

- kernel_hardening_checker/checks.py
there is an implementation of #149
a few words about logic: `OK` is `cfi=kcfi` in __cmdline__. if this parameter is not set, we looking for `CONFIG_CFI_AUTO_DEFAULT` which should be off, it is equals to  `cfi=kcfi`([reference](https://patchew.org/linux/20240501000218.work.998-kees@kernel.org/))
also for kCFI options we have some dependences, they are also added to check.
> implementation of `CONFIG_CFI_AUTO_DEFAULT `

- .github/workflows/functional_test.sh
- kernel_hardening_checker/__init__.py
implementation of of issue #158 
some **sysct** checks depend on the microarchitecture,
for example: #157 
what i did: 
- renamed the existing `detect_arch()` into `detect_arch_kconfig()` 
- implemented `detect_arch_sysctl()`.
now we can parse the `kernel.arch` **sysctl** to determine the arch.
>  implementation of `detect_arch_sysctl()`

- kernel_hardening_checker/checks.py
realised issue #153 
tested on `bullseye` image, also there is an default option for my ubutu. didnt cause any issuses with booting or something
this option can reduces chances to local privelege escalation using null-pntr
> implementation of `vm.mmap_min_addr = 65536` sysctl check

- kernel_hardening_checker/__init__.py
- kernel_hardening_checker/checks.py
reffering to #146, i implemented this cheks
we cant check maximum and minimum random offets through `sysctl` (please, see [my comments here](https://github.com/a13xp0p0v/kernel-hardening-checker/issues/146))
> implementation of `arch_mmap_rnd` checks

- .github/workflows/functional_test.sh
- kernel_hardening_checker/__init__.py
Instead of having to specify Kconfig file and `/proc/cmdline`, `--autodetect` will try to infer them.
This is related to #129, and replaces #130.
> Add an --autodetect option

- kernel_hardening_checker/__init__.py
- kernel_hardening_checker/checks.py
- kernel_hardening_checker/engine.py
- kernel_hardening_checker/test_engine.py
hello, @a13xp0p0v
this PR refers to #151
i have a few theses 
may be we shoould use this design
```Python
lsm_modules = ['module1', 'module2' ... 'moduleN']
for module in lsm_modules:
l += [KconfigCheck('self_protection', 'kspp', 'LSM', module)]
```
instead of
```Python
l += [KconfigCheck('self_protection', 'kspp', 'LSM', 'landlock')]
l += [KconfigCheck('self_protection', 'kspp', 'LSM', 'lockdown')]
l += [KconfigCheck('self_protection', 'kspp', 'LSM', 'yama')]
```
> but if we iterate this, we cant past author (kspp, a13xp0p0v, or anyone else) easily. so, its not a suggestion, just a little question
may be you meant some modules which i not commited?
how to be with `-g X86_64` ?
> parsing CONFIG_LSM option implementation

- kernel_hardening_checker/checks.py
hello, @a13xp0p0v 
i recently created a VM to test my hardening, after which i found that some of the checks have a bigger effect than expected
- `bdev_allow_write_mounted=0`
since snap uses the squashfs filesystem and creates loop devices, enabling this line may crash snap and its applications
- `kernel.modules_disabled=1`
it interrupts system startup. it should be installed only after the kernel is loaded (e.g. with systemd).
> Improved some comments-warnings

- README.md
- kernel_hardening_checker/__init__.py
- kernel_hardening_checker/engine.py
- kernel_hardening_checker/test_engine.py
Hi, I think it's a good idea to reorder the `reason` and `desired_val` tables, because `desired_val` is mostly unpredictable and there can be really long option names, for exaple cmdline parameter `lockdown=confidentiality` or `efi=disable_early_pci_dma` would tear up the output table like this:
After reordering the tables it would look a bit better:
By the way, having the desired value close to the check result seems a bit more convenient :)
I hope you will find this addition as a great one, waiting for your review!
> Reorder output tables

- kernel_hardening_checker/checks.py
Hi, looked into the parameter `perf_event_paranoid` and it seems that a value of 2 behaves like 3 in the vast majority of cases. 
Based on https://github.com/a13xp0p0v/kernel-hardening-checker/tree/master/kernel_hardening_checker/config_files/distros and CONFIG_SECURITY_PERF_EVENTS_RESTRICT (see https://lkml.org/lkml/2016/1/11/587) kconfig presence: the unique value 3 is common mostle for Debian family.
So, I think it is better to make more detailed comment
> Extend perf_event_paranoid comment
